# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
  run-automation-test:
    if: ${{ inputs.automation-test == true }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: adopt

      - name: 'Execute Automation Testing'
        run: |
          ./gradlew test

      # - name: 'Upload Test Report'
      #   uses: actions/upload-artifact@v3.1.2
      #   if: always()
      #   with:
      #     name: automation-test-artifacts
      #     path: ${{ inputs.automation-test-report-path }}
      #     if-no-files-found: error
      #     retention-days: 3
